project:
  type: book
  output-dir: docs

book:
  title: "COMP127 Notebook"
  author: "Julia Prewitt"
  date: "Fall 2024"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: notes/README.qmd
      chapters: 
      - notes/9.4-InClassActivity.qmd
      - notes/9.6-Rdg-JavaBasics.qmd
      - notes/9.9-Rdg-RKindsOfTypes.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-line-numbers: true
    code-tools: true

execute:
  cache: true
  freeze: auto
